### ISSUE TITLE
Future of the web site

### ISSUE THREAD

**Issue by MrSaints** [MrSaints/Enactus-LSESU#1]
_Really, just a personal note._

**Consideration:** Flat-file vs. database approach?

**Background:** The web site currently does not rely on any database. Content management requires manual modification of specific files which can be tedious, redundant, etc, in the long-term.

**Possible solutions:**
- ~~Re-work the entire back-end and mimic static site generators (e.g. the use of YAML front matter and Markdown to build an array of namespaces, pages and their respective contents).~~
- ~~Use and modify a static site generator (e.g. Assemble).~~
- ~~Switch over to Sails.js and utilise a database.~~
- [Express MVC](https://github.com/visionmedia/express/tree/master/examples/mvc).

**Implications:**
- **Yaml front matter and markdown:** Redundant and difficulty in separating metadata from content upon rendering (Express' render() accepts the view path, not a string / raw pre-rendered content).
- **Assemble.io:** No room - or at least, it is made more difficult - for dynamic content (e.g. forms).
- **Sails.js:** Going against initial principle to avoid reliance on database; reduced performance?

**Updates:**
- **07/01/2014:** Maintaining the status quo, but with a huge clean up. Pursuing a quasi-MVC approach.
- **09/01/2014:** Core router should be compartmentalized to allow non-GET requests to take advantage of metadata and template functions (pass instance to action function).
- **17/01/2014:** Router re-worked. Contact us page added.
- **10/02/2014:** Grunt has slowly been phased in / integrated (currently for compiling Compass / SASS files). _Generated assets should not be included in the source. They should be generated and used upon deployment (pre/post-install scripts)._
- **26/02/2014:** Grunt default, dev, and test tasks added (nearing complete automation). Express MVC model used and adapted.
- **28/04/2014:** New Express 4 released. Dependencies are out-dated.
- **05/04/2014:** Updated to Express 4. Considering a refactor of the router and Grunt tasks (see Ghost).
- **04/07/2015:** Migrated to Jekyll (static site). It is now hosted on `gh-pages`. Hopefully, this should be _easier_ to maintain. It was also a much needed migration (even if only temporary) considering Heroku's new pricing model. Travis CI and CloudFlare (HTTPS) enabled. TODO: Contact us page.

**Todo:**
- [x] Remove .bowerrc.
- [ ] Remove built components from repository.
- [x] Upgrade Bower dependencies (Foundation in particular).
- [ ] Clean up Grunt tasks (compartmentalize) and add server watch task
- [ ] CloudFlare postinstall script?
- [ ] Transfer ownership of domain and Mailgun
